kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "signalr-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    port: 80
    backends:
      - hosts: 
        {{- with .Values.ingress.hosts }}
        hosts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        destination: {{ include "blazor.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port: 80
        scheme: http
    sessionStore: cookie