apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "blazor.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.ingress.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  http:
    - route:
        - destination:
            host: {{ include "signalr-proxy.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
