kind: Secret
apiVersion: v1
metadata:
  name: {{ include "signalr-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  CIPHER_KEY: 5VHBzOnwT5XzmZJ7qy72awHHpZBbkdQ4jPTFy3+qlYC6CJKnoOLCh3lhbaqT
type: Opaque
