apiVersion: v1
kind: Service
metadata:
  name: {{ include "blazor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blazor.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http-web
  selector:
    {{- include "blazor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
