apiVersion: v1
kind: Service
metadata:
  name: {{ include "signalr-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blazor.labels" . | nindent 4 }}
    app.kubernetes.io/component: signalr-proxy
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http-web
  selector:
    {{- include "blazor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: signalr-proxy

